version: "3.8"

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db
    networks:
      - symfony

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/symfony
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:8.0.43
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-symfony}
      MYSQL_USER: ${DB_USER:-symfony}
      MYSQL_PASSWORD: ${DB_PASSWORD:-symfony}
    networks:
      - symfony


networks:
  symfony:
